name: AutoSigner

on:
  workflow_dispatch:
    inputs:
      app_name:
        required: true
      ipa_url:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create folders
        run: mkdir -p output

      - name: Download IPA
        run: |
          curl -L "${{ github.event.inputs.ipa_url }}" -o "${{ github.event.inputs.app_name }}.ipa"

      - name: Move IPA
        run: |
          mv "${{ github.event.inputs.app_name }}.ipa" output/

      - name: Generate plist (AUTO)
        run: |
          APP="${{ github.event.inputs.app_name }}"
          REPO="Karbin18/zsign"

          cat <<EOF > output/$APP.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>items</key>
            <array>
              <dict>
                <key>assets</key>
                <array>
                  <dict>
                    <key>url</key>
                    <string>https://raw.githubusercontent.com/$REPO/main/output/$APP.ipa</string>
                    <key>kind</key>
                    <string>software-package</string>
                  </dict>
                </array>
                <key>metadata</key>
                <dict>
                  <key>bundle-identifier</key>
                  <string>com.karbin.$APP</string>
                  <key>bundle-version</key>
                  <string>1.0</string>
                  <key>kind</key>
                  <string>software</string>
                  <key>title</key>
                  <string>$APP</string>
                </dict>
              </dict>
            </array>
          </dict>
          </plist>
          EOF

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: output/
